### PR TITLE
Allow React 17 in peer dependencies

### PR DESCRIPTION
**Pull request by habovh**
React 17 should not break this package, this PR simply adds React 17 to the allowed peer dependencies.

### CODE REVIEW

**Comment by Gustash** [comment]
I would rather you use the same style that the `react-native` peer dependency uses. Can you change it to that style please?

**Comment by habovh** [comment]
`react-native` peer dependency does not allow for React 16 anymore, so it is actually advisable to keep both here since the library should work just fine with both.

EDIT: I misunderstood your comment, please disregard my reply. However I'm not sure how you expect to change this. Like, including versions between 16 (inclusive) and 18 (exclusive)?

**Comment by Gustash** [comment]
> EDIT: I misunderstood your comment, please disregard my reply. However I'm not sure how you expect to change this. Like, including versions between 16 (inclusive) and 18 (exclusive)?

Yes, I think that would be fine for now 🙂 thank you

**Review by Gustash — APPROVED** [review]
@habovh thanks for this! I'll get this released ASAP

**Pull request merged**
